### ISSUE TITLE
Repo without Channel

### ISSUE THREAD

**Issue by slimslenderslacks** [atomisthqa/handlers#48]
We need a handler that responds to Commits on Repos that do not have associated channels _OR_ brand new Repos.

When this occurs, a questions should be raised in #general channel to ask for permission to create a new slack channel, or use an existing channel, to discuss activities pertaining to this repo.

**Comment by slimslenderslacks** [comment]
In other words, handlers must be capable of noticing that a Repo does not have a channel associated with it - and i have created an event that can be raised that will create this relationship.

[11:37 AM]  
The event to create the relationship is ready to go.  The logic to notice that it should be raised and the action to raise it are missing

**Comment by tanya-coding** [comment]
This might get quite noisy if handler will post a message for each commit without a repo and nobody clicks the action button.  Might seem very nag-y.  I do wonder if it makes sense to send events without repo to general but have an additional action button:  "Assign Channel" -> runs executor that raises event instead of raising a separate message with that same action and hide events.  It seems that seeing events will prompt much quicker response to assign channel

**Comment by slimslenderslacks** [comment]
my take is that noise should be controlled by the bot-service.  So there's nothing wrong with handlers that are basically saying "missing info ... still missing info ... still missing info ... still missing info" ... as long as these are not being sent as Messages.  They're just reminders that there is data still needs to be collected that team, and form for the basis for:
